"""empty message

Revision ID: 0e73325ce043
Revises: 212d9ae7dc97
Create Date: 2025-10-24 09:54:04.940816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e73325ce043'
down_revision = '212d9ae7dc97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ahorro', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ahorro_username_persona_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'persona', ['username_persona'], ['username'], ondelete='CASCADE')

    with op.batch_alter_table('emisiones', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('emisiones_username_persona_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'persona', ['username_persona'], ['username'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emisiones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('emisiones_username_persona_fkey'), 'persona', ['username_persona'], ['username'])

    with op.batch_alter_table('ahorro', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ahorro_username_persona_fkey'), 'persona', ['username_persona'], ['username'])

    # ### end Alembic commands ###
