"""initial migration

Revision ID: 1d8b0aa85725
Revises: 
Create Date: 2025-10-30 22:08:13.931521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d8b0aa85725'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persona',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('ahorro',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username_persona', sa.String(), nullable=False),
    sa.Column('ingresos', sa.Float(), nullable=False),
    sa.Column('gastos', sa.Float(), nullable=False),
    sa.Column('fecha', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['username_persona'], ['persona.username'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emisiones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username_persona', sa.String(), nullable=False),
    sa.Column('litros_combustible', sa.Float(), nullable=False),
    sa.Column('kwh_consumidos', sa.Float(), nullable=False),
    sa.Column('tipo_vehiculo', sa.String(), nullable=False),
    sa.Column('energia_renovable', sa.Boolean(), nullable=False),
    sa.Column('tipo_calefaccion', sa.String(), nullable=False),
    sa.Column('fecha', sa.String(), nullable=False),
    sa.Column('kg_co2', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['username_persona'], ['persona.username'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emisiones')
    op.drop_table('ahorro')
    op.drop_table('persona')
    # ### end Alembic commands ###
