"""empty message

Revision ID: 212d9ae7dc97
Revises: 0763d677d453
Create Date: 2025-10-21 08:38:32.548318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '212d9ae7dc97'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persona',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('ahorro',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username_persona', sa.String(), nullable=False),
    sa.Column('ingresos', sa.Float(), nullable=False),
    sa.Column('gastos', sa.Float(), nullable=False),
    sa.Column('fecha', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['username_persona'], ['persona.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emisiones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username_persona', sa.String(), nullable=False),
    sa.Column('litros_combustible', sa.Float(), nullable=False),
    sa.Column('kwh_consumidos', sa.Float(), nullable=False),
    sa.Column('tipo_vehiculo', sa.String(), nullable=False),
    sa.Column('energia_renovable', sa.Boolean(), nullable=False),
    sa.Column('tipo_calefaccion', sa.String(), nullable=False),
    sa.Column('fecha', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['username_persona'], ['persona.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
    sa.UniqueConstraint('email', name=op.f('user_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('emisiones')
    op.drop_table('ahorro')
    op.drop_table('persona')
    # ### end Alembic commands ###
