"""empty message

Revision ID: 533b2ea0db24
Revises: 0e73325ce043
Create Date: 2025-10-28 20:37:25.050295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '533b2ea0db24'
down_revision = '0e73325ce043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emisiones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kg_co2', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emisiones', schema=None) as batch_op:
        batch_op.drop_column('kg_co2')

    # ### end Alembic commands ###
